Implement chat presence notification
imadeanaccount1/wasteof.plus pull request #27
Opened 2023-07-19 18:25 UTC by Gilbert189

This PR adds the `chatPresenceNotif` add-on, which posts a message when a user enters/leaves the chat. It's based on [this gist](https://gist.github.com/Gilbert189/ab04381364c49078a3f12d9017338fd7) I made a while back.

Currently it's not working due to some permission error that I currently cannot resolve (probably since I'm running this in Firefox). 

### Things to do before merging
- [ ] Fix the permission error

2023-07-19 19:02 UTC, imadeanaccount1 commented
This looks like a really cool contribution! Thank you and I can't wait until it's in a mergeable state! 🤩

2023-07-20 08:15 UTC, Gilbert189 commented
I can confirm that the permission error is only on Firefox, since I've tried it on Chrome and it doesn't have the permission error.
However, now there's another problem; the `window` doesn't actually have the `$nuxt` key (on wasteof3 `socket` is `undefined`)

2023-07-21 18:22 UTC, Gilbert189 commented
I figured out that injecting the notify script to `<head>` would work instead of executing it directly on `addon.js`. A weird hack, sure; but I see other addons doing this exact thing so I guess I'm not the only one that thought of it.

And now, it works... on Chrome at least. Firefox still had that permission problem. But since Firefox compatibility isn't on high priority yet, I'll split it off to a different section.

2023-07-21 18:43 UTC, imadeanaccount1 commented
@all-contributors please add @Gilbert189 for code, ideas

2023-07-21 18:48 UTC, imadeanaccount1 requested changes
Are all of these new permissions really necessary?
"notifications",
        "tabs",
        "idle",
        "webNavigation",
        "webRequest",
        "webRequestBlocking",
        "unlimitedStorage",
        "storage",
        "contextMenus",
        "clipboardWrite",
        "cookies",
        "downloads",
        "<all_urls>"

2023-07-21 18:49 UTC, imadeanaccount1 commented
https://github.com/all-contributors please add @Gilbert189 for code, ideas

2023-07-21 18:52 UTC, imadeanaccount1 commented
@all-contributors please add @Gilbert189 for code, ideas

2023-07-21 19:07 UTC, imadeanaccount1 commented
@Gilbert189 
Can't test right now because wasteof's down but I'll try to work on merging sometime when the site gets back up 😕

I may also wait until PR #22 is merged (it adds new changes to the structure of addon.json files). See more info in the CONTRIBUTING.md file of the relevant branch.

2023-07-21 20:43 UTC, imadeanaccount1 commented on manifest_firefox.json
Too many permissions

2023-07-21 21:08 UTC, imadeanaccount1 commented
@Gilbert189 I just confirmed that the firefox bug will be fixed in a PR I will create tonight. It is unrelated to your code, though.

2023-07-21 23:20 UTC, imadeanaccount1 approved these changes

2023-07-21 23:20 UTC, merged

2023-07-22 00:54 UTC, Gilbert189 commented on manifest_firefox.json
Yeah, that was my "solution" to the permission error for Firefox